#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048M

#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

# https://github.com/InsertKoinIO/koin/issues/2133
kotlin.native.cacheKind=none


RELEASE_STORE_FILE=upload-keystore.jks
RELEASE_STORE_PASSWORD=liscePadaJesenJe
RELEASE_KEY_ALIAS=upload
RELEASE_KEY_PASSWORD=liscePadaJesenJe
